apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: kibishii-csi-storage-class
provisioner: file.csi.azure.com
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
mountOptions:
  - dir_mode=0640
  - file_mode=0640
  - uid=0
  - gid=0
  - mfsymlinks
  - cache=strict
  - nosharesock
parameters:
  skuName: Standard_LRS
